/*
 * This file is part of the coreboot project.
 *
 * Copyright 2013 Google Inc.
 * Copyright (C) 2017 Samsung Electronics
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <arch/io.h>
#include <soc/trustzone.h>
#include <soc/cpu.h>

/* Setting TZPC[TrustZone Protection Controller]
 * We pretty much disable it all, as the kernel
 * expects it that way -- and that's not the default.
 */
void trustzone_init(void)
{

#if IS_ENABLED(CONFIG_TZ_BLK_CAM_CSI)
	write32((void *)TRAV_SYSREG_CAM_CSI + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CAM_CSI + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_CAM_DPRX)
	write32((void *)TRAV_BUS_P_CAM_DPRX0 + SECURITY1,     TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CAM_DPRX0 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CAM_DPRX0 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_CAM_DPRX1 + SECURITY1,     TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CAM_DPRX1 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CAM_DPRX1 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_CMU)
	write32((void *)TRAV_SYSREG_CMU + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CMU + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_CORE_GT)
	write32((void *)TRAV_SYSREG_CORE + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CORE + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_CPUCL)
	write32((void *)TRAV_SYSREG_CPUCL0 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CPUCL1 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CPUCL2 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CPUCL0 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CPUCL1 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_CPUCL2 + TZPC_PROT1SET, TRUSTZONE_DISABLE);

#endif

#if IS_ENABLED(CONFIG_TZ_BLK_FSYS0)
	write32((void *)TRAV_BUS_P_FSYS0 + SECURITY2, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_FSYS0 + SECURITY3, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_FSYS0 + SECURITY4, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_FSYS0 + SECURITY5, TRUSTZONE_DISABLE);
#if IS_ENABLED(CONFIG_TZ_BLK_FSYS0_NSFMP)
	write32((void *)TRAV_SYSREG_FSYS0 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
#else
	write32((void *)TRAV_SYSREG_FSYS0 + TZPC_PROT0SET, TRUSTZONE_DISABLE_EXCEPT_FMP);
#endif
	write32((void *)TRAV_SYSREG_FSYS0 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_FSYS0 + TZPC_FSYS0_0, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_FSYS0 + TZPC_FSYS0_1, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_FSYS1)
	write32((void *)TRAV_BUS_S0_FSYS1 + SECURITY0, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_S0_FSYS1 + SECURITY1, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_S0_FSYS1 + SECURITY2, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_S0_FSYS1 + SECURITY3, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_FSYS1 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_FSYS1 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_GPU)
	write32((void *)TRAV_BUS_P_GPU  + SECURITY1,     TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_GPU + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_GPU + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_IMEM)
	write32((void *)TRAV_BUS_P_IMEM + SECURITY1, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_IMEM + SECURITY2, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_IMEM + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_IMEM + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_ISP)
	write32((void *)TRAV_BUS_P_ISP + SECURITY1, TRUSTZONE_DISABLE);
	write32((void *)TRAV_BUS_P_ISP + SECURITY2, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_ISP + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_ISP + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_MFC)
	write32((void *)TRAV_SYSREG_MFC + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MFC + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_MIF0)
	write32((void *)TRAV_SYSREG_MIF0 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF1 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF2 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF3 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF4 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF5 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF6 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF7 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF0 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF1 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF2 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF3 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF4 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF5 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF6 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_MIF7 + TZPC_PROT1SET, TRUSTZONE_DISABLE);

#endif

#if IS_ENABLED(CONFIG_TZ_BLK_PERIC)
	write32((void *)TRAV_BUS_P_PERIC + SECURITY3, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_PERIC + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_PERIC + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_0, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_1, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_2, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_3, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_4, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PERIC + TZPC_PERIC_5, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_PMU)
	write32((void *)TRAV_SYSREG_PMU + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_PMU + TZPC_PROT1SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_GPIO_PMU   + TZPC_PMU_0,    TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_TRIP0)
	write32((void *)TRAV_SYSREG_TRIP0 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_TRIP0 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif

#if IS_ENABLED(CONFIG_TZ_BLK_TRIP1)
	write32((void *)TRAV_SYSREG_TRIP1 + TZPC_PROT0SET, TRUSTZONE_DISABLE);
	write32((void *)TRAV_SYSREG_TRIP1 + TZPC_PROT1SET, TRUSTZONE_DISABLE);
#endif
}
