#ifndef _MAILBOX_A72_SCS_INTERFACE_H_
#define _MAILBOX_A72_SCS_INTERFACE_H_

//#ifdef __aarch64__
    #define A72_MAILBOX                 (0x10080000)
    #define A72_MAILBOX_TO_A72_INT      (A72_MAILBOX + 0x0008)
    #define A72_MAILBOX_TO_SCS_INT      (A72_MAILBOX + 0x001C)
    #define A72_MAILBOX_TO_A72_ISSR_LO  (A72_MAILBOX + 0x0080)
    #define A72_MAILBOX_TO_SCS_ISSR_LO  (A72_MAILBOX + 0x00C0)
    #define A72_MAILBOX_TO_A72_ISSR_HI  (A72_MAILBOX + 0x0100)
    #define A72_MAILBOX_TO_SCS_ISSR_HI  (A72_MAILBOX + 0x0140)
    #define A72_MAILBOX_TO_A72_SEM_LO   (A72_MAILBOX + 0x0180)
    #define A72_MAILBOX_TO_SCS_SEM_LO   (A72_MAILBOX + 0x018C)
    #define A72_MAILBOX_TO_A72_SEM_HI   (A72_MAILBOX + 0x0198)
    #define A72_MAILBOX_TO_SCS_SEM_HI   (A72_MAILBOX + 0x01A4)
//#endif

#define MAILBOX_SERVICE_ID_FILE 1
//#define MAILBOX_SERVICE_ID_DCCM 2
//#define MAILBOX_SERVICE_ID_PMIC 3
#define MAILBOX_SERVICE_ID_KEYS 4
#define MAILBOX_SERVICE_ID_OTP  5
#define MAILBOX_SERVICE_ID_SLOG 6
//#define MAILBOX_SERVICE_ID_ELOG 7
#define MAILBOX_SERVICE_ID_BOOT 8
//#define MAILBOX_SERVICE_ID_CAN  9
//#define MAILBOX_SERVICE_ID_TMU  10
//#define MAILBOX_SERVICE_ID_RECOVERY 11
//#define MAILBOX_SERVICE_ID_SLEEP 12
#define MAILBOX_SERVICE_ID_ETHERNET 13

#define FILE_SERVICE_CMD_GET_VERSION        0

#define FILE_SERVICE_CMD_GET_FILE_SIZE      1

#define FILE_SERVICE_CMD_GET_FILE           2

#define FILE_SERVICE_RSP_GET_FILE       (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_GET_FILE)

#define FILE_SERVICE_CMD_UPDATE_FILE        3

#define FILE_SERVICE_RSP_UPDATE_FILE       (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_UPDATE_FILE)

#define FILE_SERVICE_CMD_GET_COREBOOT_SIZE  4

#define FILE_SERVICE_CMD_LOAD_COREBOOT      5

#define FILE_SERVICE_RSP_LOAD_COREBOOT      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_LOAD_COREBOOT)

#define FILE_SERVICE_CMD_SWAP_COREBOOT      6

#define FILE_SERVICE_RSP_SWAP_COREBOOT      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_SWAP_COREBOOT)

#define FILE_SERVICE_CMD_GET_BOOTBLOCK_SIZE  7

#define FILE_SERVICE_CMD_LOAD_BOOTBLOCK      8

#define FILE_SERVICE_RSP_LOAD_BOOTBLOCK      (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_LOAD_BOOTBLOCK)

#define FILE_SERVICE_CMD_UPDATE_FIRMWARE    9

#define FILE_SERVICE_RSP_UPDATE_FIRMWARE    (MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_UPDATE_FIRMWARE)

#define FILE_SERVICE_CMD_VERIFY_FILE    10

#define FILE_SERVICE_RSP_VERIFY_FILE	(MBOX_COMMAND_RESPONSE_ID | FILE_SERVICE_CMD_VERIFY_FILE)

#define FILE_SERVICE_FILE_ROOT_CA_ID            0x01
#define FILE_SERVICE_FILE_SCS_BL1_ID            0x02
#define FILE_SERVICE_FILE_CRL_ID                0x03
#define FILE_SERVICE_FILE_SCS_BL2_CRT_ID        0x10
#define FILE_SERVICE_FILE_SCS_BL2_ID            0x11
#define FILE_SERVICE_FILE_SMS_BL1_CRT_ID        0x20
#define FILE_SERVICE_FILE_SMS_BL1_ID            0x21

#define FILE_SERVICE_FILE_A72_BL1_CRT_ID        0x30
#define FILE_SERVICE_FILE_A72_BL1_ID            0x31
#define FILE_SERVICE_FILE_A72_COREBOOT_A_CRT_ID 0x32
#define FILE_SERVICE_FILE_A72_COREBOOT_A_ID     0x33
#define FILE_SERVICE_FILE_A72_COREBOOT_B_CRT_ID 0x34
#define FILE_SERVICE_FILE_A72_COREBOOT_B_ID     0x35
#define FILE_SERVICE_FILE_A72_CONFIG_ID         0x36
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_A_CRT_ID 0x37
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_A_ID     0x38
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_B_CRT_ID 0x39
#define FILE_SERVICE_FILE_A72_BOOTBLOCK_B_ID     0x3A

#define KEYS_SERVICE_CMD_GET_VERSION    0

#define KEYS_SERVICE_CMD_SIGN           1

#define KEYS_SERVICE_RSP_SIGN       (MBOX_COMMAND_RESPONSE_ID | KEYS_SERVICE_CMD_SIGN)

#define KEYS_SERVICE_CMD_VERIFY         2

#define KEYS_SERVICE_RSP_VERIFY      (MBOX_COMMAND_RESPONSE_ID | KEYS_SERVICE_CMD_SIGN)

#define OTP_SERVICE_CMD_GET_VERSION        0

#define OTP_SERVICE_CMD_GET_CHIP_ID      1

#define OTP_SERVICE_CMD_FUSE_DDR_INFO 19

#define OTP_SERVICE_CMD_GET_DDR_INFO 20

#define SLOG_SERVICE_CMD_GET_VERSION        0

#define LOG_MSG_LENGTH_IN_32BIT		12

#define SLOG_SERVICE_CMD_LOG_MESSAGE        1

#define SLOG_SERVICE_RSP_LOG_MESSAGE        (MBOX_COMMAND_RESPONSE_ID | SLOG_SERVICE_CMD_LOG_MESSAGE)

#define BOOT_SERVICE_CMD_GET_VERSION    0

#define BOOT_SERVICE_CMD_GET_TURBO_ID   1

#define BOOT_SERVICE_CMD_GET_OTP_STATE   2

#define BOOT_SERVICE_CMD_GET_A72_STATE   3

#define BOOT_SERVICE_CMD_GET_BUILD_VERSION   4

#define BOOT_SERVICE_CMD_GET_BUILD_VERSION_STRING   5

#define BOOT_SERVICE_CMD_GET_PCBA_VERSION               6

#define BOOT_SERVICE_CMD_GET_BUILD_GIT_HASH   7

#define BOOT_SERVICE_CMD_GET_IMAGE_TYPE   8

#define BOOT_SERVICE_CMD_GET_SMS_BUILD_VERSION   9

#define BOOT_SERVICE_CMD_GET_A72BL1_BUILD_VERSION   10

#define BOOT_SERVICE_CMD_GET_A72BOOTBLOCK_BUILD_VERSION   11

#define BOOT_SERVICE_CMD_GET_A72COREBOOT_BUILD_VERSION   12

#define BOOT_SERVICE_CMD_GET_SCSBL1_BUILD_VERSION   13

#define BOOT_SERVICE_CMD_GET_SCSBL1_BUILD_VERSION_STRING   14

#define BOOT_SERVICE_CMD_GET_SCSBL1_BUILD_GIT_HASH   15

#define BOOT_SERVICE_CMD_GET_SCSBL1_IMAGE_TYPE   16

#define BOOT_SERVICE_CMD_IS_RECOVERY_MODE   22

#define BOOT_SERVICE_CMD_GET_RECOVERY_BOOT_COUNTERS   28

#define BOOT_SERVICE_CMD_GET_A72_WARM_RESET 29

#define A72_BOOT_FROM_COLD_BOOT		0
#define A72_BOOT_FROM_WARM_RESET	1
#define A72_BOOT_FROM_DELAYED_WARM_BOOT	2

#define BOOT_SERVICE_CMD_GET_BL1_DATA_VER   38

#define ETHERNET_SERVICE_CMD_GET_VERSION        0

#define ETHERNET_SERVICE_CMD_POWER_ON_INIT      1

#define ETHERNET_SERVICE_RSP_POWER_ON_INIT       (MBOX_COMMAND_RESPONSE_ID | ETHERNET_SERVICE_CMD_POWER_ON_INIT)

#define A72_MAILBOX_STATUS_OK                                   0x0

#define A72_MAILBOX_STATUS_REQUEST_PENDING                      0x1

#define A72_MAILBOX_STATUS_INVALID_ARGUMENTS                    0xFFFF1000

#define A72_MAILBOX_STATUS_NOT_SUPPORTED                        0xFFFF1001

#define A72_MAILBOX_STATUS_BUSY                                 0xFFFF1002

#define A72_MAILBOX_STATUS_INVALID_COMMAND                      0xFFFFFFFE

#define A72_MAILBOX_STATUS_INVALID_REQUEST                      0xFFFFFFFF

#endif
