#ifndef MAILBOX_A72_SMS_INTERFACE_H
#define MAILBOX_A72_SMS_INTERFACE_H

//#define MAILBOX_SERVICE_ID_FILE 1
//#define MAILBOX_SERVICE_ID_DCCM 2
#define MAILBOX_SERVICE_ID_PMIC 3
//#define MAILBOX_SERVICE_ID_KEYS 4
//#define MAILBOX_SERVICE_ID_OTP  5
//#define MAILBOX_SERVICE_ID_SLOG 6
//#define MAILBOX_SERVICE_ID_ELOG 7
#define MAILBOX_SERVICE_ID_BOOT 8
#define MAILBOX_SERVICE_ID_CAN  9
#define MAILBOX_SERVICE_ID_TMU  10
#define MAILBOX_SERVICE_ID_RECOVERY 11
#define MAILBOX_SERVICE_ID_SLEEP 12


#define PMIC_SERVICE_CMD_GET_VERSION        0

#define PMIC_SERVICE_CMD_POWER_SET        1

#define PMIC_SERVICE_RSP_POWER_SET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_POWER_SET)

#define PMIC_SERVICE_CMD_POWER_GET        2

#define PMIC_SERVICE_RSP_POWER_GET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_POWER_GET)

#define PMIC_SERVICE_POWER_12V0_SW          0x01
#define PMIC_SERVICE_POWER_INT              0x02
#define PMIC_SERVICE_POWER_CPU              0x03
#define PMIC_SERVICE_POWER_GPU              0x04
#define PMIC_SERVICE_POWER_TRIP0            0x05
#define PMIC_SERVICE_POWER_TRIP1            0x06
#define PMIC_SERVICE_POWER_1V8_DDR          0x07
#define PMIC_SERVICE_POWER_1V1_DDR          0x08
#define PMIC_SERVICE_POWER_IO_0V9           0x09
#define PMIC_SERVICE_POWER_IO_1V8           0x0A
#define PMIC_SERVICE_POWER_IO_3V3           0x0B
#define PMIC_SERVICE_POWER_IO_1V2           0x0C

#define PMIC_SERVICE_CMD_VOLTAGE_SET        3

#define PMIC_SERVICE_RSP_VOLTAGE_SET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_VOLTAGE_SET)

#define PMIC_SERVICE_CMD_VOLTAGE_GET        4

#define PMIC_SERVICE_RSP_VOLTAGE_GET        (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_VOLTAGE_GET)

#define PMIC_SERVICE_VOLTAGE_TURBO_INT      0x00000001
#define PMIC_SERVICE_VOLTAGE_TURBO_CPU      0x00000002
#define PMIC_SERVICE_VOLTAGE_TURBO_GPU      0x00000003
#define PMIC_SERVICE_VOLTAGE_TURBO_TRIP0    0x00000004
#define PMIC_SERVICE_VOLTAGE_TURBO_TRIP1    0x00000005

#define PMIC_SERVICE_CMD_A72_RESET          5

#define PMIC_SERVICE_RSP_A72_RESET       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_RESET)

#define PMIC_SERVICE_CMD_A72_POWER_OFF      6

#define PMIC_SERVICE_RSP_A72_POWER_OFF       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_POWER_OFF)

#define PMIC_SERVICE_CMD_A72_POWER_ON      7

#define PMIC_SERVICE_RSP_A72_POWER_ON       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_A72_POWER_ON)

#define PMIC_SERVICE_CMD_PMIC_RESET      8

#define PMIC_SERVICE_RSP_PMIC_RESET       (MBOX_COMMAND_RESPONSE_ID | PMIC_SERVICE_CMD_PMIC_RESET)

#define PMIC_SERVICE_CMD_GET_HPM_ASV        9

#define CAN_SERVICE_CMD_GET_VERSION			0

#define CAN_SERVICE_CMD_SET_REGION          1

#define TMU_SERVICE_CMD_START_TRACE			0

#define TMU_SERVICE_CMD_STOP_TRACE			1

#define TMU_SERVICE_CMD_SET_SAMPLE_RATE     2

#define TMU_SERVICE_CMD_PRINT_TRACE         3

#define TMU_SERVICE_CMD_GET_CURRENT_TEMPS   4

#define TMU_SERVICE_CMD_GET_TRACE_SAMPLES   5

#define RECOVERY_SERVICE_CMD_GET_VERSION        0

#define RECOVERY_SERVICE_CMD_GET_MODE           1

#define RECOVERY_SERVICE_VERSION                1U

#define SLEEP_SERVICE_CMD_GET_VERSION		0U

#define SLEEP_SERVICE_CMD_ENTER_SLEEP		1U

#define SLEEP_SERVICE_CMD_EXIT_SLEEP        2U

#define SLEEP_SERVICE_VERSION               1U

#define BOOT_SERVICE_CMD_GET_VERSION        0

#define BOOT_SERVICE_CMD_GET_BUILD_GIT_HASH   7

#define BOOT_SERVICE_CMD_SET_AP_HEALTHY   17

#define BOOT_SERVICE_CMD_SET_AP_CONTINUE   18

#define BOOT_SERVICE_CMD_SET_AP_BOOTED   19

#define BOOT_SERVICE_CMD_SET_AP_BOOTED_OS   20

#define BOOT_SERVICE_CMD_SET_AP_BOOTING   21

#define SMS_MAILBOX_STATUS_OK                                   0x0

#define SMS_MAILBOX_STATUS_REQUEST_PENDING                      0x1

#define SMS_MAILBOX_STATUS_INVALID_ARGUMENTS                    0xFFFF1000

#define SMS_MAILBOX_STATUS_NOT_SUPPORTED                        0xFFFF1001

#define SMS_MAILBOX_STATUS_BUSY                                 0xFFFF1002

#define SMS_MAILBOX_STATUS_INVALID_COMMAND                      0xFFFFFFFE

#define SMS_MAILBOX_STATUS_INVALID_REQUEST                      0xFFFFFFFF

#endif
