/*
 * This file is part of the coreboot project.
 *
 * Copyright (C) 2017 Samsung Electronics
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */
#ifndef _UFSHCI_VS_REG_H_
#define _UFSHCI_VS_REG_H_

/* Vendor specific */
#define UFSHCI_VS_TXPRDT_ENTRY_SIZE	0x1100
#define UFSHCI_VS_RXPRDT_ENTRY_SIZE	0x1104
#define UFSHCI_VS_1US_TO_CNT_VAL_1US	0x110C
#define UFSHCI_VS_INVALID_UPIU_CTRL	0x1110
#define UFSHCI_VS_INVALID_UPIU_BADDR	0x1114
#define UFSHCI_VS_INVALID_UPIU_UBADDR	0x1118
#define UFSHCI_VS_INVALID_UTMR_OFFSET_ADDR	0x111C
#define UFSHCI_VS_INVALID_UTR_OFFSET_ADDR	0x1120
#define UFSHCI_VS_INVALID_DIN_OFFSET_ADDR	0x1124
#define UFSHCI_VS_IS	0x1138
#define UFSHCI_VS_IE	0x113C
#define UFSHCI_VS_UTRL_NEXUS_TYPE	0x1140
#define UFSHCI_VS_UMTRL_NEXUS_TYPE	0x1144
#define UFSHCI_VS_SW_RST	0x1150
#define UFSHCI_VS_LINK_VERSION	0x1154
#define UFSHCI_VS_RS_FMPIU_MATCH_ERROR_CODE	0x115C
#define UFSHCI_VS_DATA_REORDER	0x1160
#define UFSHCI_VS_AXIDMA_RWDATA_BURST_LEN	0x116C
#define UFSHCI_VS_GPIO_OUT	0x1170
#define UFSHCI_VS_WRITE_DMA_CTRL	0x1174
#define UFSHCI_VS_DEFS_ERROR_EN_PA_LAYER	0x1178
#define UFSHCI_VS_DEFS_ERROR_EN_DL_LAYER	0x117C
#define UFSHCI_VS_DEFS_ERROR_EN_N_LAYER	0x1180
#define UFSHCI_VS_DEFS_ERROR_EN_T_LAYER	0x1184
#define UFSHCI_VS_DEFS_ERROR_EN_DME_LAYER	0x1188
#define UFSHCI_VS_UFSHCI_V2P1_CTRL	0X118C
#define UFSHCI_VS_REQ_HOLD	0x11AC
#define UFSHCI_VS_CLKSTOP_CTRL	0x11B0
#define UFSHCI_VS_MISC	0x11B4
#define UFSHCI_VS_FSM_MONITOR	0x11C0 /* cross check this is not in xls */
#define UFSHCI_VS_PRDT_HIT_RATIO	0x11C4
#define UFSHCI_VS_DMA0_MONITOR_STATE	0x11C8
#define UFSHCI_VS_DMA0_MONITOR_CNT	0x11CC
#define UFSHCI_VS_DMA1_MONITOR_STATE	0x11D0
#define UFSHCI_VS_DMA1_MONITOR_CNT	0x11D4
#define UFSHCI_VS_AXI_DMA_IF_CTRL	0x11F8
#define UFSHCI_VS_UFS_ACG_DISABLE	0x11FC
#define UFSHCI_VS_IOP_ACG_DISABLE	0x1200 /* check: this is reserved in trav */
#define UFSHCI_VS_UFS_UDPD	0x1204
#define UFSHCI_VS_MPHY_REFCLK_SEL	0x1208
#define UFSHCI_VS_SMU_ABORT_MATCH_INFO	0x120C

//trav mphy registers
#define CMN_REG01	(0x0004)

//trav unipro register
#define DME_POWERMODE_IND_RESULT	0x000078EC
#define DME_LINKSTARTUP_CNF_RESULT	0x00007854

/* UFSHCI_VS_UFSHCI_V2P1_CTRL register */
#define UFSHCI_VS_IA_TICK_SEL	SHIFT(1, 16)
#define UFSHCI_VS_DFES_OCS_EN	SHIFT(1, 0)

#define UFSHCI_VS_IS_RX_UPIU_LEN_ERROR	SHIFT(1, 18)
#define UFSHCI_VS_IS_RX_UPIU_HIT_ERROR	SHIFT(1, 19)
#define UFSHCI_VS_IS_UFS_IDLE_INDICATOR	SHIFT(1, 20)
#define UFSHCI_VS_IS_UIC_REQ_SEQ_ERROR	SHIFT(1, 21) /* REVD2*/
#define UFSHCI_VS_IS_SMU_MISMATCH	SHIFT(1, 22)
#define UFSHCI_VS_IS_UFS_PM_INT	SHIFT(1, 23)
#define UFSHCI_VS_IS_FMP_FAULT	SHIFT(1, 24)
#define UFSHCI_VS_IS_DBR_TIMER_INT	SHIFT(1, 25)
#define UFSHCI_VS_IS_DBR_DUPLICATION_INT	SHIFT(1, 27)
#define UFSHCI_VS_IS_MPHY_PCS_INT	SHIFT(1, 28)
#define UFSHCI_VS_IS_UNIPRO_INTERRUPT	SHIFT(1, 31)

#define UFSHCI_VS_IS_ERR (UFSHCI_VS_IS_RX_UPIU_LEN_ERROR\
		| UFSHCI_VS_IS_RX_UPIU_HIT_ERROR\
		| UFSHCI_VS_IS_SMU_MISMATCH\
		| UFSHCI_VS_IS_UFS_PM_INT\
		| UFSHCI_VS_IS_FMP_FAULT)

#define UFSHCI_VS_IE_UTRL0_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 0)
#define UFSHCI_VS_IE_UTRL1_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 1)
#define UFSHCI_VS_IE_UTRL2_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 2)
#define UFSHCI_VS_IE_UTRL3_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 3)
#define UFSHCI_VS_IE_UTRL4_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 4)
#define UFSHCI_VS_IE_UTRL5_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 5)
#define UFSHCI_VS_IE_UTRL6_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 6)
#define UFSHCI_VS_IE_UTRL7_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 7)
#define UFSHCI_VS_IE_UTRL8_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 8)
#define UFSHCI_VS_IE_UTRL9_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 9)
#define UFSHCI_VS_IE_UTRL10_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 10)
#define UFSHCI_VS_IE_UTRL11_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 11)
#define UFSHCI_VS_IE_UTRL12_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 12)
#define UFSHCI_VS_IE_UTRL13_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 13)
#define UFSHCI_VS_IE_UTRL14_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 14)
#define UFSHCI_VS_IE_UTRL15_RESP_UPIU_ACCEPT_wPHASE	SHIFT(1, 15)

#define UFSHCI_VS_IE_RX_UPIU_LEN_ERROR	SHIFT(1, 18)
#define UFSHCI_VS_IE_RX_UPIU_HIT_ERROR	SHIFT(1, 19)
#define UFSHCI_VS_IE_UFS_IDLE_INDICATOR	SHIFT(1, 20)
#define UFSHCI_VS_IE_UIC_REQ_SEQ_ERROR	SHIFT(1, 21)
#define UFSHCI_VS_IE_SMU_MISMATCH	SHIFT(1, 22)
#define UFSHCI_VS_IE_UFS_PM_INT	SHIFT(1, 23)
#define UFSHCI_VS_IE_FMP_FAULT	SHIFT(1, 24)
#define UFSHCI_VS_IE_DBR_TIMER_INT	SHIFT(1, 25)
#define UFSHCI_VS_IE_DBR_DUPLICATION_INT	SHIFT(1, 27)
#define UFSHCI_VS_IE_MPHY_PCS_INT	SHIFT(1, 28)
#define UFSHCI_VS_IE_UNIPRO_INTERRUPT	SHIFT(1, 31)

#define MISC_REFCLK_STOP_EN	SHIFT(1, 7)
#define MISC_REFCLKOUT_STOP_EN	SHIFT(1, 11)
#define MPHY_APBCLK_STOP_EN	SHIFT(1, 3)
#define REFCLKOUT_STOP_EN_BIT_POS	(4)
#define REFCLKOUT_STOP_EN	SHIFT(1, 4)

/* AXIDMA_RWDATA_BURST_LEN register */
#define WLU_ENABLE_BIT_POS	(31)
#define WLU_BUSRT_SIZE_BIT_POS	(27)
#define AXIDMA_BURST_SIZE_BIT_POS	(0)
#define WLU_ENABLE	SHIFT(0x1UL, WLU_ENABLE_BIT_POS)
#define WLU_BUSRT_SIZE	SHIFT(0xF, WLU_BUSRT_SIZE_BIT_POS)
#define AXIDMA_BURST_SIZE	SHIFT(0xF, AXIDMA_BURST_SIZE_BIT_POS)

#endif /* _UFSHCI_REG_H_ */
